apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
data:
  E_BUDGET_DB_HOSTNAME: "{{ .Values.database.hostname }}"
  E_BUDGET_DB_PORT: "{{ .Values.database.port }}"
  E_BUDGET_DB_NAME: "{{ .Values.database.name }}"
