apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    app: {{ .Values.appName }}
    tier: be
spec:
  replicas: {{ .Values.numReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: be
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: be
    spec:
      containers:
        - name: {{ .Values.appName }}-container
          image: leojgpereira/e-budget-be
          imagePullPolicy: Always
          ports:
            - containerPort: 8080